### ISSUE TITLE
Exception raised when no views in window.

### ISSUE THREAD

**Issue by mattst** [adamchainz/SublimeSwitchViewInGroup#1]
Exception raised when no views in window.

An "index out of range" exception get raised when there are no views in the active window. I only discovered it by accident when I hit the keys while in the wrong window with the console open.

Not worth cloning, pulling, and pushing, for 2 lines of code to fix.

    def move_view_in_group(window, amount):
        active_group = window.active_group()
        active_view = window.active_view()
        group, index = window.get_view_index(active_view)
        active_group_views = window.views_in_group(active_group)

        # No views in window.
        if index == -1:
            return

        index += amount
        if index == len(active_group_views):
            index = 0
        elif index == -1:
            index = len(active_group_views) - 1

        activate = active_group_views[index]
        window.focus_view(activate)

BTW thanks for the useful plugin.

**Comment by adamchainz** [comment]
You can edit on github!

**Comment by mattst** [comment]
Done.

That's cool, I had no idea it was that easy. What a perfect amount of code to enter for a first time test.

Thanks.
