### ISSUE TITLE
stack skip with Ctrl holding 

### ISSUE THREAD

**Issue by Fenzland** [adamchainz/SublimeSwitchViewInGroup#4]
Suppose we have 4 sheets: s0, s1, s2, s3. And we are now at s0. 
Now we hold on `Ctrl` and press `PageDown` 3 times. 
We now switch to s3. 
Now we press `Ctrl + Tab`, we go back to s0.

Keeping holding `Ctrl` make the stack skip s1 and s2.

But if we bind `Ctrl + PageDown` to `next_view_in_group`, we not go back to s2 but not s0 when `Ctrl + Tab`.

**Comment by adamchainz** [comment]
Hi

I bound "switch view in group" to ctrl + tab so I don't have this problem. I simply didn't like Sublime's default ctrl + tab behaviour.

I don't think there's anything we can do for you here I'm afraid. Sublime maintains the order of sheets for its default ctrl + tab internally. But feel free to look into developing the plugin yourself - I'd welcome a PR that fixes this for you. Closing the issue for now.

Thanks,

Adam
